model:
  learning_rate: 8e-4 # from MAR for img gen paper
  target: world_mar.models.mar.WorldMAR
  params:
    vae_config:
      target: world_mar.oasis_utils.vae.ViT_L_20_Shallow_Encoder 
      params:
        load_from_ckpt: checkpoints/oasis/vit-l-20.safetensors
