model:
  learning_rate: 5e-5
  target: world_mar.models.mar.WorldMAR
  params:
    vae_config:
      target: world_mar.oasis_utils.vae.ViT_L_20_Shallow_Encoder 
      params:
        load_from_ckpt: checkpoints/oasis/vit-l-20.safetensors
    img_height: 360
    img_width: 640
    num_frames: 3
    num_mem_frames: 1
    num_prev_frames: 2
    patch_size: 2
    vae_embed_dim: 16
    vae_seq_h: 18
    vae_seq_w: 32
    st_embed_dim: 256
    encoder_depth: 8
    decoder_depth: 8
    encoder_num_heads: 8
    decoder_num_heads: 8
    diffloss_w: 256
    diffloss_d: 3
    num_sampling_steps: '100'
    diffusion_batch_mul: 4
    prev_masking_rate: 0.25
    mask_ratio_min: 0.7
    proj_dropout: 0.1
    attn_dropout: 0.1
    gradient_clip_val: 1.0
    warmup_steps: 13500

dataloader:
  target: world_mar.dataset.dataloader.MinecraftDataModule
  params:
    dataset_dir: "data/minecraft-7x/"
    batch_sz: 48
    prev_distance: 1
    memory_distance: 1000
    memory_size: 100
    train_split: 0.99 # 0.01 for val
    num_mem_frames: 1
    num_prev_frames: 1
    num_workers: 8