_wandb:
    value:
        cli_version: 0.19.10
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 55
                - 63
                - 103
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.9.21
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
